global:
  scrape_interval: 10s

external_labels:
  cluster: "cluster-1"
  prometheus: "prometheus-1"

scrape_configs:
  - job_name: "pushgateway"
    static_configs:
      - targets: ["host.docker.internal:9093"]
